apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: signalprocess-secrets
  namespace: dapr-signalprocess
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../dapr/components/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - signalprocessservice
  - notificationservice